ta bort endepunkt for /arbeidsgivere
navikt/helsearbeidsgiver-inntektsmelding pull request #124
Opened 2023-05-22 12:35 UTC by mortenbyhring

2023-05-22 13:22 UTC, bjerga approved these changes

2023-05-22 13:22 UTC, bjerga commented on api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/arbeidsgivere/ArbeidsgivereRoute.kt
> -            Key.BEHOV to listOf(BehovType.ARBEIDSGIVERE).toJson(BehovType.serializer()),
Dette er den eneste løseren som bruker `BehovType.ARBEIDSGIVERE`. Det burde også fjernes.

2023-05-22 13:57 UTC, bjerga requested changes

2023-05-23 08:28 UTC, bjerga commented on api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/arbeidsgivere/ArbeidsgivereRoute.kt
> -            Key.BEHOV to listOf(BehovType.ARBEIDSGIVERE).toJson(BehovType.serializer()),
Endepunktet kommer trolig tilbake. Beholder behovtypen og løseren til da.

2023-05-23 08:28 UTC, mortenbyhring commented on api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/arbeidsgivere/ArbeidsgivereRoute.kt
> -            Key.BEHOV to listOf(BehovType.ARBEIDSGIVERE).toJson(BehovType.serializer()),
Mulig det blir nødvendig å gjeninnføre endepunkt senere, så venter med å fjerne løser...

2023-05-23 08:52 UTC, merged