Ny iterasjon av eksperimentell river
navikt/helsearbeidsgiver-inntektsmelding pull request #331
Opened 2023-10-23 09:27 UTC by bjerga

Altinn-løseren blir ikke brukt i dag, så dette skal ikke ha noen påvirkning på noen som helst flyter.

2023-11-23 14:08 UTC, bjerga commented on altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeser.kt
> +            DataFelt.ARBEIDSFORHOLD to rettigheter.toJson(AltinnOrganisasjon.serializer().set())
La til ny nå.

2023-11-27 12:06 UTC, b162214 requested changes

2023-11-27 12:06 UTC, b162214 commented on altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeser.kt
> +        Melding(
EventName?

2023-11-27 12:06 UTC, b162214 commented on altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeser.kt
> +        return mapOf(
EventName?

2023-11-27 12:30 UTC, bjerga commented on felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
> -        .associate { (key, value) -> key.str to value.toJsonNode() }
`associate` er en funksjon for å gjøre lister om til maps. Den fungerte før når `messageFields` var en liste, men nå, i denne funksjonen, er det allerede et map. Da må man bruke andre `mapKeys` og `mapValues` for samme effekt.

2023-11-27 12:37 UTC, bjerga commented on altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeser.kt
> +        Melding(
La til nå.

2023-11-27 12:42 UTC, b162214 approved these changes

2023-11-27 13:37 UTC, merged