Fjern utdatert journalføring-river
navikt/helsearbeidsgiver-inntektsmelding pull request #444
Opened 2024-02-21 12:25 UTC by bjerga

2024-02-23 06:43 UTC, mortenbyhring commented
Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. 
(En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). 
Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.

2024-02-23 06:45 UTC, mortenbyhring requested changes
Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?

2024-02-23 07:30 UTC, bjerga commented
> Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. (En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.

> Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?

@mortenbyhring Dette virker for meg som en begrensning på systemet vårt. Er det mulig å løse på andre måter? Kunne man lagt til et felt ved feil som aktiverer rekjøring? Typ. `Key.RETRY_ON_FAIL to JournalfoerImRiver`.

2024-02-23 08:00 UTC, mortenbyhring commented
> > Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. (En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.
> 
> > Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?
> 
> @mortenbyhring Dette virker for meg som en begrensning på systemet vårt. Er det mulig å løse på andre måter? Kunne man lagt til et felt ved feil som aktiverer rekjøring? Typ. `Key.RETRY_ON_FAIL to JournalfoerImRiver`.

Det er en mulig løsning ja. Ville vel bare laget det som en optional boolean som sendes med der vi i dag har rekjør-behovene

2024-02-23 08:12 UTC, bjerga commented
> > > Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. (En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.
> > 
> > 
> > > Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?
> > 
> > 
> > @mortenbyhring Dette virker for meg som en begrensning på systemet vårt. Er det mulig å løse på andre måter? Kunne man lagt til et felt ved feil som aktiverer rekjøring? Typ. `Key.RETRY_ON_FAIL to JournalfoerImRiver`.
> 
> Det er en mulig løsning ja. Ville vel bare laget det som en optional boolean som sendes med der vi i dag har rekjør-behovene

@mortenbyhring Jeg tenkte også først på en boolean, men er det ikke en fordel å kunne identifisere den feilende riveren på et vis? En event kan jo trigge flere rivers.

2024-02-23 09:41 UTC, mortenbyhring commented
> > > > Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. (En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.
> > > 
> > > 
> > > > Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?
> > > 
> > > 
> > > @mortenbyhring Dette virker for meg som en begrensning på systemet vårt. Er det mulig å løse på andre måter? Kunne man lagt til et felt ved feil som aktiverer rekjøring? Typ. `Key.RETRY_ON_FAIL to JournalfoerImRiver`.
> > 
> > 
> > Det er en mulig løsning ja. Ville vel bare laget det som en optional boolean som sendes med der vi i dag har rekjør-behovene
> 
> @mortenbyhring Jeg tenkte også først på en boolean, men er det ikke en fordel å kunne identifisere den feilende riveren på et vis? En event kan jo trigge flere rivers.

Rekjøringen trenger vel ikke ha noe forhold til hvilken river noe kommer fra.. 
Forresten: En grunn til å beholde Behov på rekjøringslogikken er at da er det enkelt å se og konfigurere opp hva som skal rekjøres ett sted - i feilbehandleren, slik som nå. 
Ved å innføre et rekjør-flagg, blir dette spredt i alle som sender, det er litt mer uoversiktlig.

2024-02-28 08:02 UTC, mortenbyhring commented
> > > > > Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. (En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.
> > > > 
> > > > 
> > > > > Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?
> > > > 
> > > > 
> > > > @mortenbyhring Dette virker for meg som en begrensning på systemet vårt. Er det mulig å løse på andre måter? Kunne man lagt til et felt ved feil som aktiverer rekjøring? Typ. `Key.RETRY_ON_FAIL to JournalfoerImRiver`.
> > > 
> > > 
> > > Det er en mulig løsning ja. Ville vel bare laget det som en optional boolean som sendes med der vi i dag har rekjør-behovene
> > 
> > 
> > @mortenbyhring Jeg tenkte også først på en boolean, men er det ikke en fordel å kunne identifisere den feilende riveren på et vis? En event kan jo trigge flere rivers.
> 
> Rekjøringen trenger vel ikke ha noe forhold til hvilken river noe kommer fra.. Forresten: En grunn til å beholde Behov på rekjøringslogikken er at da er det enkelt å se og konfigurere opp hva som skal rekjøres ett sted - i feilbehandleren, slik som nå. Ved å innføre et rekjør-flagg, blir dette spredt i alle som sender, det er litt mer uoversiktlig.

Jo, man må vel i så fall identifisere feilet river, i tilfeller der bare deler av en kjede skal rekjøres - men det betyr jo at *alle* løsere må ha sin egen identifikator *og* inkludere en sjekk på om det er seg selv hver gang de får en hvilken som helst pakke med rekjør-flagget. De må også inkludere identifikator i fail-pakken, så da må dette også utvides. Det kan så klart løses, men synes ikke det er særlig elegant, all den tid Behov gjorde dette såpass enkelt tidligere.

2024-03-08 14:02 UTC, bjerga commented
> > > > > > Ser nå at dette vil brekke feilhåndtering / rekjøring - for å vite at noe skal rekjøres, er man avhengig av at det er et Behov. (En Event vil ikke være nok, siden denne typisk kan videresendes / deles mellom flere løsere). Den nye måten å journalføre på - med JournalførIMRiver vil altså aldri plukkes opp av rekjøring dersom den feiler.
> > > > > 
> > > > > 
> > > > > > Uten behov, ingen rekjøring. Fortsette med BehovType.JOURNALFOER i ny river kanskje?
> > > > > 
> > > > > 
> > > > > @mortenbyhring Dette virker for meg som en begrensning på systemet vårt. Er det mulig å løse på andre måter? Kunne man lagt til et felt ved feil som aktiverer rekjøring? Typ. `Key.RETRY_ON_FAIL to JournalfoerImRiver`.
> > > > 
> > > > 
> > > > Det er en mulig løsning ja. Ville vel bare laget det som en optional boolean som sendes med der vi i dag har rekjør-behovene
> > > 
> > > 
> > > @mortenbyhring Jeg tenkte også først på en boolean, men er det ikke en fordel å kunne identifisere den feilende riveren på et vis? En event kan jo trigge flere rivers.
> > 
> > 
> > Rekjøringen trenger vel ikke ha noe forhold til hvilken river noe kommer fra.. Forresten: En grunn til å beholde Behov på rekjøringslogikken er at da er det enkelt å se og konfigurere opp hva som skal rekjøres ett sted - i feilbehandleren, slik som nå. Ved å innføre et rekjør-flagg, blir dette spredt i alle som sender, det er litt mer uoversiktlig.
> 
> Jo, man må vel i så fall identifisere feilet river, i tilfeller der bare deler av en kjede skal rekjøres - men det betyr jo at _alle_ løsere må ha sin egen identifikator _og_ inkludere en sjekk på om det er seg selv hver gang de får en hvilken som helst pakke med rekjør-flagget. De må også inkludere identifikator i fail-pakken, så da må dette også utvides. Det kan så klart løses, men synes ikke det er særlig elegant, all den tid Behov gjorde dette såpass enkelt tidligere.

Nå har vi diskutert oss frem til at rivers i den asynkrone delen av Simba skal gå bort fra å bruke behovtyper og heller være mer basert på eventtyper. Riverne må ha en ID for retries, men slipper å forholde seg til behov, som de gjør i dag.

2024-03-11 07:47 UTC, mortenbyhring approved these changes

2024-03-12 12:56 UTC, merged