Felles løser event
navikt/helsearbeidsgiver-inntektsmelding pull request #92
Opened 2023-04-24 13:52 UTC by alpet

2023-04-24 15:00 UTC, b162214 requested changes

2023-04-24 15:00 UTC, b162214 commented on pdl/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/FulltNavnLøser.kt
> +            ?: " kan ikke finne uuid/forespørselID"
Hva er forsellen på første case og andre case?

2023-04-24 15:09 UTC, alpet commented on pdl/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/FulltNavnLøser.kt
> +            ?: " kan ikke finne uuid/forespørselID"
oi...... det stor UUID i begge tilfeller :D   Ooooppppsss......

2023-04-24 15:13 UTC, alpet commented on helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLøser.kt
Du tenker på det at meldingen er gjenbrukt fra akkumulatoren?

2023-04-25 07:48 UTC, b162214 approved these changes

2023-04-25 10:43 UTC, merged